MVC_KHO/MVC_QLKHO/Models/PhieuNhap.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_QLKHO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuNhap
    {
        public PhieuNhap()
        {
            this.LoHangs = new HashSet<LoHang>();
        }
    
        public int ID_PhieuNhap { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public string ID_NhanVien { get; set; }
        public string Note { get; set; }
    
        public virtual ICollection<LoHang> LoHangs { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}

MVC_KHO/MVC_QLKHO/Controllers/CTNhapKhoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC_QLKHO.Models;
using ClosedXML.Excel;
using System.IO;

namespace MVC_QLKHO.Controllers
{
    public class CTNhapKhoController : BaseController
    {
        public ActionResult Index(int ID_PhieuNhap, string export_excel = null)
        {
            var phieuNhap = new dbQLKhoEntities().PhieuNhaps.ToList().FirstOrDefault(q => q.ID_PhieuNhap == ID_PhieuNhap);
            ViewBag.phieuNhap = phieuNhap;
            var data = new dbQLKhoEntities().LoHangs.ToList().Where(q => q.ID_PhieuNhap == ID_PhieuNhap && q.Status != 0).ToList();
            if (string.IsNullOrWhiteSpace(export_excel) == false && data != null && data.Count > 0)
            {
                XLWorkbook wb = new XLWorkbook(Server.MapPath(@"\Content\Export\nhapkho.xlsx"));
                var ws = wb.Worksheet(1);
                var index_row = 5;

                ws.Row(index_row++).Cell(5).Value = phieuNhap.ID_PhieuNhap;
                ws.Row(index_row++).Cell(5).Value = phieuNhap.ThoiGian;
                ws.Row(index_row++).Cell(5).Value = string.Format("{0} - {1}", phieuNhap.NhanVien.MaNV, phieuNhap.NhanVien.TenNV);

                index_row = 10;
                for (int i = 0; i < data.Count; i++)
                {
                    var item = data[i];
                    var index_col = 1;
                    ws.Row(index_row).Cell(index_col++).Value = i + 1;
                    ws.Row(index_row).Cell(index_col++).Value = item.MaLoHang;
                    ws.Row(index_row).Cell(index_col++).Value = item.MaHH;
                    ws.Row(index_row).Cell(index_col++).Value = item.NSX;
                    ws.Row(index_row).Cell(index_col++).Value = item.HSD;
                    ws.Row(index_row).Cell(index_col++).Value = item.SoLuong;
                    ws.Row(index_row).Cell(index_col++).Value = item.ID_NhaKho;
                    ws.Row(index_row).Cell(index_col++).Value = item.MaNCC;
                    ws.Row(index_row).Cell(index_col++).Value = string.Format("Tầng {0} - Hàng {1} - Cột {2}", item.Tang, item.Hang, item.Cot);
                }

                using (MemoryStream stream = new MemoryStream())
                {
                    wb.SaveAs(stream);
                    return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
                }
            }
            return View(data);
        }
    }
}

MVC_KHO/MVC_QLKHO/Controllers/PhieuNhapController.cs
using MVC_QLKHO.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_QLKHO.Controllers
{
    public class PhieuNhapController : BaseController
    {
        //
        // GET: /PhieuNhap/
        public ActionResult Index(DateTime? TimeStart, DateTime? TimeEnd)
        {
            var data = new dbQLKhoEntities().PhieuNhaps.ToList();
            if (TimeStart.HasValue)
            {
                data = data.Where(q => q.ThoiGian.Value >= TimeStart.Value).ToList();
            }
            if (TimeEnd.HasValue)
            {
                data = data.Where(q => q.ThoiGian.Value <= TimeEnd.Value).ToList();
            }
            return View(data);
        }
    }
}

MVC_KHO/MVC_QLKHO/Views/PhieuNhap/Index.cshtml
@model IEnumerable<MVC_QLKHO.Models.PhieuNhap>

@{
    ViewBag.Title = "DANH SÁCH PHIẾU NHẬP";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="panel panel-primary">
    <div class="panel-heading">@ViewBag.Title</div>
    <div class="panel-body">
        <p>
            <a href="@Url.Action("Edit")" class="btn btn-success"> <i class="fa fa-plus"></i> Thêm mới</a>
        </p>
        <div class="row col-md-12" style="margin: 9px">
            @using (Html.BeginForm())
            {
                <div class="col-md-3">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-calendar"></i> Từ ngày</span>
                        <input type="date" name="TimeStart" class="form-control">
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-calendar"></i> Tới ngày</span>
                        <input type="date" name="TimeEnd" class="form-control">
                    </div>
                </div>
                <div class="col-md-2">
                    <button class="btn btn-primary" name="filter" value="filter"><i class="fa fa-filter"></i> Lọc</button>
                </div>
            }
        </div>

        <table class="table table-bordered" id="m-table">
            <thead>
                <tr>
                    <th>
                        THỜI GIAN
                    </th>
                    <th>
                        MÃ PHIẾU NHẬP
                    </th>
                    <th>
                        NHÂN VIÊN NHẬP KHO
                    </th>
                    <th>
                        GHI CHÚ
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.ThoiGian)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.ID_PhieuNhap)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.NhanVien.TenNV)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Note)
                        </td>
                        <td>
                            <a href="@Url.Action("Index", "CTNhapKho", new { ID_PhieuNhap = item.ID_PhieuNhap })" class="btn btn-bitbucket"> <i class="fa fa-edit"></i> Hóa đơn</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

@section css{
    <link href="~/Content/theme/vendor/datatables-responsive/dataTables.responsive.css" rel="stylesheet" />
    <link href="~/Content/theme/vendor/datatables/css/dataTables.bootstrap.min.css" rel="stylesheet" />
}

@section js{
    <script src="~/Content/theme/vendor/datatables/js/jquery.dataTables.min.js"></script>
    <script src="~/Content/theme/vendor/datatables/js/dataTables.bootstrap.min.js"></script>
    <script>
        $($("#m-table").dataTable());
    </script>
}